In [41]:
# Importing stack tools 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path = "/home/madhav/workstation/Lab/DataSet/w1.csv"
df = pd.read_csv(path)
print(df.shape)

df.head()

(10000, 12)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

# Exploratory Data analysis

Making founational approach with collecting as much as information possible with the dataset.

In [2]:
# Q1 : How many ? are present into the dataset
# Assuming your DataFrame is named df
unknown_count = (df == "?").sum().sum()
print(f"Number of unknown values: {unknown_count}")

Number of unknown values: 1823

In [3]:
# converting to nans
import numpy as np

df.replace("?", np.nan, inplace=True)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [4]:
# fetch a perticular element from the dataset with iloc based on indexing

df.iloc[546,7]

np.int64(3)

In [5]:
# fetch unique features from the locality feature of the dataset
df['Locality'].unique()

<StringArray>
[    'Waterbury',    'Bridgeport',     'Greenwich',       'Norwalk',
             nan,     'Fairfield', 'West Hartford',      'Stamford']
Length: 8, dtype: str

In [43]:
# How many features have missing nan values ?

# Show only columns with NaNs and their respective counts
nan_counts = df.isna().sum()

print(nan_counts[nan_counts > 0])

len(df)

Locality           1253
Estimated Value    1243
carpet_area        1229
dtype: int64

10000

In [44]:
min_valid_values = len(df.columns) - 2

# Drop rows that don't meet the threshold
df_cleaned = df.dropna(thresh=min_valid_values)

len(df_cleaned)

9978

In [46]:
df = df.dropna()

len(df)

6700