In [32]:
# loc and iloc based precise extraction from data frame

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(10,4), index=list('abcdefghij'), columns=list('ABCD'))
df

          A         B         C         D
a  0.960422  0.296770  0.933724  0.213884
b  0.762705  0.558899  0.830279  0.576313
c  0.809708  0.390083  0.516462  0.922323
d  0.693238  0.976063  0.714939  0.752529
e  0.662297  0.669418  0.548000  0.508239
f  0.012630  0.110289  0.161038  0.590221
g  0.874633  0.172455  0.903182  0.167132
h  0.216454  0.185185  0.269873  0.180963
i  0.144220  0.968459  0.968243  0.883812
j  0.317063  0.004677  0.081237  0.457066

In [33]:
# Making precise selection with loc wayout with columns

df.loc['d', 'A':'C'] # Precise selection of the dataset

A    0.693238
B    0.976063
C    0.714939
Name: d, dtype: float64

In [45]:
# using lambda function with selection of data through a data selection :)
selector = lambda df: df["A"]  > 0.8
df.loc[selector]

          A         B         C         D
a  0.960422  0.296770  0.933724  0.213884
c  0.809708  0.390083  0.516462  0.922323
g  0.874633  0.172455  0.903182  0.167132