# Editing DataFrame

Simple dictionary based editing into the core data frame unit

In [20]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    np.random.rand(10,4), index=range(0,10), columns=list("ABCD")
)

df

          A         B         C         D
0  0.481332  0.618936  0.894644  0.253196
1  0.640331  0.835699  0.383512  0.369604
2  0.161717  0.723938  0.044796  0.486186
3  0.339452  0.274429  0.235172  0.439329
4  0.976385  0.323740  0.400410  0.373466
5  0.952394  0.731129  0.589429  0.355952
6  0.564102  0.220686  0.613881  0.049125
7  0.289998  0.131522  0.769460  0.588144
8  0.447266  0.412438  0.630443  0.367198
9  0.973126  0.475847  0.037568  0.595277

In [21]:
# New columns and DF editing
df['Addition'] = 100 * df['A']
'''
If the name does not exist then it would be added to the dataframe
we can also edit the existing data frame with simple dict like flow

Since editing is really straight forward
we must need to have a copy of the original dataset before doing something into

We need to read weather its original or its copy
'''
df.loc[2, 'Addition'] = 50
# lock with location based on a condition and edit them
case = df['A'] < 0.5
df.loc[case, 'A']=0 # Need to be precise about what are we doing into

df # New edited data frame with new column

          A         B         C         D   Addition
0  0.000000  0.618936  0.894644  0.253196  48.133193
1  0.640331  0.835699  0.383512  0.369604  64.033131
2  0.000000  0.723938  0.044796  0.486186  50.000000
3  0.000000  0.274429  0.235172  0.439329  33.945242
4  0.976385  0.323740  0.400410  0.373466  97.638491
5  0.952394  0.731129  0.589429  0.355952  95.239401
6  0.564102  0.220686  0.613881  0.049125  56.410226
7  0.000000  0.131522  0.769460  0.588144  28.999786
8  0.000000  0.412438  0.630443  0.367198  44.726641
9  0.973126  0.475847  0.037568  0.595277  97.312597

In [26]:
new_entries = [
    "vrindavan",
    "mathura",
    "agra",
    "firozabad",
    "akhbarpur",
    "indexing",
    "selection",
    "droping",
    "editing",
    "pandas"
]
df['places'] = new_entries

df

          A         B         C         D   Addition     places
0  0.000000  0.618936  0.894644  0.253196  48.133193  vrindavan
1  0.640331  0.835699  0.383512  0.369604  64.033131    mathura
2  0.000000  0.723938  0.044796  0.486186  50.000000       agra
3  0.000000  0.274429  0.235172  0.439329  33.945242  firozabad
4  0.976385  0.323740  0.400410  0.373466  97.638491  akhbarpur
5  0.952394  0.731129  0.589429  0.355952  95.239401   indexing
6  0.564102  0.220686  0.613881  0.049125  56.410226  selection
7  0.000000  0.131522  0.769460  0.588144  28.999786    droping
8  0.000000  0.412438  0.630443  0.367198  44.726641    editing
9  0.973126  0.475847  0.037568  0.595277  97.312597     pandas

In [34]:
# Conditional selection with isin function
filter_topics = df['places'].isin(['pandas','editing','droping','indexing'])
'''
Indexing with reference

Need to know which to target
where to lock in :)
'''
print(filter_topics) # Specifically made with places while declaring
df.loc[filter_topics]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8     True
9     True
Name: places, dtype: bool

          A         B         C         D   Addition    places
5  0.952394  0.731129  0.589429  0.355952  95.239401  indexing
7  0.000000  0.131522  0.769460  0.588144  28.999786   droping
8  0.000000  0.412438  0.630443  0.367198  44.726641   editing
9  0.973126  0.475847  0.037568  0.595277  97.312597    pandas

In [37]:
# Deleting columns
'''
Removing rows or columns by specific label
with inplace operation it would do into the DB itself

by default returns a copy of the df
we can also suppress error through error parameter
it would be raised when the column or label is not found
'''
df.drop('A', axis=1)

          B         C         D   Addition     places
0  0.618936  0.894644  0.253196  48.133193  vrindavan
1  0.835699  0.383512  0.369604  64.033131    mathura
2  0.723938  0.044796  0.486186  50.000000       agra
3  0.274429  0.235172  0.439329  33.945242  firozabad
4  0.323740  0.400410  0.373466  97.638491  akhbarpur
5  0.731129  0.589429  0.355952  95.239401   indexing
6  0.220686  0.613881  0.049125  56.410226  selection
7  0.131522  0.769460  0.588144  28.999786    droping
8  0.412438  0.630443  0.367198  44.726641    editing
9  0.475847  0.037568  0.595277  97.312597     pandas

In [50]:
# sample 
print(df.sample(2))

df

          A         B         C         D   Addition     places
4  0.976385  0.323740  0.400410  0.373466  97.638491  akhbarpur
5  0.952394  0.731129  0.589429  0.355952  95.239401   indexing

          A         B         C         D   Addition     places
0  0.000000  0.618936  0.894644  0.253196  48.133193  vrindavan
1  0.640331  0.835699  0.383512  0.369604  64.033131    mathura
2  0.000000  0.723938  0.044796  0.486186  50.000000       agra
3  0.000000  0.274429  0.235172  0.439329  33.945242  firozabad
4  0.976385  0.323740  0.400410  0.373466  97.638491  akhbarpur
5  0.952394  0.731129  0.589429  0.355952  95.239401   indexing
6  0.564102  0.220686  0.613881  0.049125  56.410226  selection
7  0.000000  0.131522  0.769460  0.588144  28.999786    droping
8  0.000000  0.412438  0.630443  0.367198  44.726641    editing
9  0.973126  0.475847  0.037568  0.595277  97.312597     pandas

In [49]:
# Data operation with multistage effects